export { default as logoDark } from './logo-dark.svg';
export { default as logoIconWhite } from './logo-icon-white.svg';
export { default as logo } from './logo.svg';
export { default as mail } from './mail.png';
export { default as mail2x } from './mail@2x.png';
export { default as watchlistArrow } from './watchlist-arrow.png';
export { default as watchlistArrow2x } from './watchlist-arrow@2x.png';
export { default as watchlistArrow3x } from './watchlist-arrow@3x.png';
export { default as traderBadge } from './trader-badge.svg';
